media: img
content:
  - name: posts
    label: Nyheter
    type: collection
    path: _nyheter
    fields:
      - { name: title, label: Titel, type: string }
      - { name: author, label: Författare, type: select, options: {
          values: [ Linus, Simon, Ulrik, Jonas ]
        }}
      - { name: date, label: Datum, type: date }
      - { name: image, label: Bild, type: image }
      - { name: description, label: Beskrivning, type: string, options: { maxlength: 160 }}
      - { name: body, label: Brödtext, type: rich-text }